#This function is to take a multiple sequence alignment (MSAs) and determine if they are the same size. 
#The sequences need to be the same size in order to generate a square matrix for calculation.
#
#Input: msa <- a multiple sequence alignment read in from a file
#
#same_size Function: Check to see if all sequences in the file are the same length
#


#Input customizaed multiple sequence alignment
msa <- c('HHHHHQSEFIKDSKASIELRNFYFNRDFRQEGASQSKAEEWAQGFLLRYESGYTEGTIGFGVDAIGLLGVKLDSSPDRSGTGLLKRDRETGRAQDDYGEGITAKLRASKSTLKIGTLTPKLPVIMPNDSRLLPQTFQGGALNSMEIDGLTLDAGRLKKVNQRDSSDNEDMTITGGGKRQIVVRSGLTSDKFDFAGGSYKWTDNLSTSYHYGKLDNFYKQHYLGLVHTLPIADKQSLKSDIRWARSTDDGSSNVDNKALNAMFTYSLGYHAFGVGYQKMSGDTGFAYINGADPYLVNFIIGDFANKDEKSWQARYDYNFAGVGIPGLTFMTRYVKGDNIDLLTTSGEGKEWERDMDIAYVFQSGPLKNLGVKWRNATMRTNYTNDYDENRLIVSYTLPL-', 'AGFLEDSKASLETRNFYMNRDFRDGPGQSKREEWAQGFILNLQSGYTQGTVGFGLDAMGMLGVKLDSGRGRSGTGLLPKDSDGRAPDTYSKLGLTAKVKVSQSELKVGTLIPKLPSVQPNNGRIFPQIFEGALLTSKEIKDLGFTAGRLEKTKIRDSSDSEDLALNDKNGRFAGVSADHFDLGGLDYKLTDQLTASYHYSNLQDVYRQHFVGLLHSWPIGPGELTSDLRFARSTDSGSAKAGGIDNKSLNGMFTYSLGNHAFGAAWQRMNGDDAFPYLEGSNPYLVNFVQVNDFAGPKERSWQLRYDYDFVGLGIPGLTFMTRYVKGDNVELAGQSGEGREWERNTELQYVFQSGALKNLGIRWRNATFRSNFTRDIDENRLIVSYTLPIWGGHHHHHH', 'EFLADSSAHLDLRNFYQLRDYRQHDAPQSQAGNWSQGFVLRLQSGFTGGPLGFGLDATGLLGVKLDSGRGRSNDGTLPFGANSKEPVDDYSHLGLTAKLRYSQTQLQVGILMPQLPVAFRDDVRLLPQTFDGALLTSSEIEGLTLTAGQLWKSRTRESAGSDDMYIMGRDKAHASDEFNLAGATYAFTPRLSASYYYGQLKDIYRQHYLGLLHTLPLGEGLSLRSDLRYFDSGEDGAAISGPVDNRNLNAMLTLRAGAHAFGIGVQKMIGNDAFPVLNGYTTPYVANLMAYQTFTRPQEKSWQLRYDYDFAGLGLPGLNLMTRYVQGRDIDRGAGRADDSEWERNTDLSYVIQSGPLKSVALKWRNITYRSRYGADLDENRFIVNYTLKLWGGHHHHHH')

#Function that checks to see if the length of each sequence is the same
same_size <- function(msa){
check <- TRUE
  #Loop that checks each sequences from position 2 on
  #Position 2 is chosen because I check the sequence at i with the sequence at i-1 (so position 2 with position 1)
  for(i in 2:length(msa)) {
    if(nchar(msa[i-1]) == nchar(msa[i])) {
      check <- TRUE
    }
    else {
      check <- FALSE
      #If at any point our sequences aren't the same size, this breaks the loop and keeps check = FALSE
      break
    }
  }
#If our checking variable is true, then our sequences are all the same size, if not then they are not
if (check == TRUE){
  cat("PASS")
}
else{
  cat("FAIL")
}
return(check)
} 

is_same_size <- same_size(msa)

